part of 'app_pages.dart';

abstract class Routes {
  static const SPLASH = _Paths.SPLASH;
  static const INTRO = _Paths.INTRO;
  static const ENROLL_COMPANY = _Paths.ENROLL_COMPANY;
  static const SETUP_COMPANY = _Paths.SETUP_COMPANY;
  static const GET_LOCATION = _Paths.GET_LOCATION;
  static const ENROLL_SUCCESS = _Paths.ENROLL_SUCCESS;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const CREATE_STAFF = _Paths.CREATE_STAFF;
  static const HOME = _Paths.HOME;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const ACCOUNT = _Paths.ACCOUNT;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const LEAVE_REQUEST = _Paths.LEAVE_REQUEST;
  static const OVERTIME_REQUEST = _Paths.OVERTIME_REQUEST;
  static const LOGIN = _Paths.LOGIN;
  static const OVERVIEW = _Paths.OVERVIEW;
  static const LOGIN_SET_PASSWORD = _Paths.LOGIN_SET_PASSWORD;
  static const SERVICE = _Paths.SERVICE;
  static const SERVICE_DETAIL = _Paths.SERVICE_DETAIL;
  static const REGISTER = _Paths.REGISTER;
  static const ATTENDANCE_MANAGE = _Paths.ATTENDANCE_MANAGE;
  static const STAFF_MANAGE = _Paths.STAFF_MANAGE;
  static const PROFILE_STAFF = _Paths.PROFILE_STAFF;
  static const WORKING_HOURS_STATISTICS = _Paths.WORKING_HOURS_STATISTICS;
  static const ATTENDANCE_STAFF = _Paths.ATTENDANCE_STAFF;
  static const DEPARTMENT_MANAGE = _Paths.DEPARTMENT_MANAGE;
  static const SHIFT_MANAGE = _Paths.SHIFT_MANAGE;
  static const DASHBOARD_STATISTICS = _Paths.DASHBOARD_STATISTICS;
  static const COMPANY_PROFILE = _Paths.COMPANY_PROFILE;
  static const LEAVE_REQUESTS_MANAGE_ = _Paths.LEAVE_REQUESTS_MANAGE;
  static const OVERTIME_REQUESTS_MANAGE = _Paths.OVERTIME_REQUESTS_MANAGE;
  static const LEAVE_REQUEST_HISTORY = _Paths.LEAVE_REQUEST_HISTORY;
  static const OVERTIME_REQUEST_HISTORY = _Paths.OVERTIME_REQUEST_HISTORY;
  static const UPDATE_PROFILE = _Paths.UPDATE_PROFILE;
  static const COMPANY_SETTING = _Paths.COMPANY_SETTING;
  static const COMPANY_LOCATION = _Paths.COMPANY_LOCATION;
  static const LANGUAGE = _Paths.LANGUAGE;
  static const DEFAULT_SHIFT = _Paths.DEFAULT_SHIFT;
  static const DEFAULT_CHECKIN = _Paths.DEFAULT_CHECKIN;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  Routes._();
}

abstract class _Paths {
  static const SPLASH = '/splash';
  static const INTRO = '/intro';
  static const ENROLL_COMPANY = '/enroll_company';
  static const SETUP_COMPANY = '/setup_company';
  static const GET_LOCATION = '/get_location';
  static const ENROLL_SUCCESS = '/enroll_success';
  static const SIGN_UP = '/sign_up';
  static const CREATE_STAFF = '/create_staff';
  static const HOME = '/home';
  static const ATTENDANCE = '/attendance';
  static const ACCOUNT = '/account';
  static const CHANGE_PASSWORD = '/change_password';
  static const LEAVE_REQUEST = '/leave_request';
  static const OVERTIME_REQUEST = '/overtime_request';
  static const OVERVIEW = '/overview';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const LOGIN_SET_PASSWORD = '/login_set_password';
  static const SERVICE = '/service';
  static const SERVICE_DETAIL = '/service_detail';
  static const ATTENDANCE_MANAGE = '/attendance_manage';
  static const STAFF_MANAGE = '/staff_manage';
  static const PROFILE_STAFF = '/profile_staff';
  static const WORKING_HOURS_STATISTICS = '/working_hours_statistics';
  static const ATTENDANCE_STAFF = '/attendance_staff';
  static const DEPARTMENT_MANAGE = '/department_manage';
  static const SHIFT_MANAGE = '/shift_manage';
  static const DASHBOARD_STATISTICS = '/dashboard_statistics';
  static const COMPANY_PROFILE = '/company_profile';
  static const LEAVE_REQUESTS_MANAGE = '/leave_requests_manage';
  static const OVERTIME_REQUESTS_MANAGE = '/overtime_requests_manage';
  static const LEAVE_REQUEST_HISTORY = '/leave_request_history';
  static const OVERTIME_REQUEST_HISTORY = '/overtime_request_history';
  static const UPDATE_PROFILE = '/update_profile';
  static const COMPANY_SETTING = '/company_setting';
  static const COMPANY_LOCATION = '/company_location';
  static const LANGUAGE = '/language';
  static const DEFAULT_SHIFT = '/default_shift';
  static const DEFAULT_CHECKIN = '/default_checkin';
  static const FORGOT_PASSWORD = '/forgot_password';
}
